name: Test CLI
on:
  push:
    branches:
      - '*'
jobs:
  lint:
    name: Lint sources
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
  test:
    name: Test sources
    strategy:
      fail-fast: false
      max-parallel: 3
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - name: Test Go
        run: go test -race ./...
  test-status:
    name: Test status
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - name: Set Check Status Success
        uses: Sibz/github-status-action@v1.1.1
        with:
          context: test-status
          authToken: ${{ secrets.GITHUB_TOKEN }}
          state: success
